version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

volumes:
  keycloak-postgres:
